# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: USMEAT
    url: https://http://usmeatlive.mx/
  - name: UCA
    url: https://moodle.ucags.edu.mx/
  - name: MASTERMANUAL
    url: https://mastermanual.mx/

status-website:
  baseUrl: /Monitor # where "repo" is your repository name
  name: Monitor Designa

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
